title:               Connor J Robbins
url:                 https://www.connorjrobbins.com
include:             ['_pages']
exclude:             ['_includes/notes_graph.json']
# You may need to change the base URL depending on your deploy configuration.
# Specifically, when using GitHub Pages, the baseurl should point to where GitHub
# Pages deploys your repository (which is usually the repository name).
baseurl:             ''

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension:  false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
# open_external_links_in_new_tab: true

relative_permalinks: false

plugins:
  - jekyll-redirect-from
  - jekyll-last-modified-at
  - jekyll-target-blank

target-blank:
  # add_css_classes: ext-link
  noopener: false
  noreferrer: false
  rel: external

sass:
  sass_dir:          _sass
  style:            :compressed

collections_dir: collections
collections:
  posts:
    output: true
    permalink: /blog/:slug
  newsletters:
    output: true
    permalink: /newsletter/:slug
  notes:
    output: true
    permalink: /notes/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "newsletters"
    values:
      layout: "post"
  - scope:
      type: "notes"
    values:
      layout: "note"
